services:
  homeassistantui:
    image: homeassistantui
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "8040:8040"
      - "8042:8042"
    environment:
      - ASPNETCORE_HTTP_PORT=8040
      - ASPNETCORE_URLS=https://+:8042;http://+:8040
      - ASPNETCORE_HTTPS_PORT=8042
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - home-assistant-network

networks:
  home-assistant-network:
    driver: bridge
